[platformio]
default_envs = waveshare-7b
src_dir = firmware/7b

[env:waveshare-7b]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv
upload_port = COM9
upload_speed = 921600
monitor_speed = 115200
extra_scripts = pre:scripts/build_7b.py
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DCORE_DEBUG_LEVEL=3
    -DUI_7B_HARDWARE=1
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_CONF_PATH=../../../firmware/7b/lv_conf.h
lib_deps =
    h2zero/NimBLE-Arduino@2.5.0
