#ifndef LV_CONF_H
#define LV_CONF_H
#define LV_COLOR_DEPTH 16
#define LV_COLOR_16_SWAP 0
#define LV_MEM_SIZE (4U * 1024U * 1024U)
#define LV_FONT_MONTSERRAT_12 1
#define LV_FONT_MONTSERRAT_16 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_24 1
#define LV_FONT_MONTSERRAT_48 1
#define LV_FONT_DEFAULT &lv_font_montserrat_16
#define LV_USE_SNAPSHOT 1
#define LV_SPRINTF_USE_FLOAT 1
#define LV_BUILD_EXAMPLES 0
#define LV_USE_VIDEO 0
#define LV_USE_GUIDER_SIMULATOR 0
#endif
